version: '3.9'

x-db-variables: &db-variables
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

x-app-variables: &app-variables
  <<: *db-variables
  POSTGRES_HOST: postgres
  WAIT_HOSTS: postgres:5432

services:
  app:
    build: .
    image: etsy-scraper:latest 
    command: sh -c "/wait && python src/manage.py makemigrations && python src/manage.py migrate && python src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    environment: *app-variables
    depends_on:
      - postgres
    ports:
      - "8000:8000"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment: *db-variables